### ISSUE TITLE
ContentProvider exception after resetting test solo run

### ISSUE THREAD

**Issue by Anaminus** [Anaminus/roblox-bug-tracker#228]
1. Open a new place and press the new play solo button.
2. Press the reset button immediately (spam until it's active).

There is a chance that one or more of the following errors will occur:

```
ContentProvider callback exception: Can't submit requested task type
ContentProvider callback exception: Unable to dispatch task
```

There is also a chance that a crash message will appear.

**Comment by The0neThe0nly** [comment]
I have attempted to reproduce this but the issue seems to be fixed. Can someone confirm?

**Comment by Anaminus** [comment]
I can't get it to crash, but the ContentProvider error still happens.

**Comment by osmanre263** [comment]
After the recent Roblox update, I believe was yesterday 3-12-2016, I started getting this error. This error specifically happens when I include SetAsync for a datastore. I can provide code if you so require. I have been able to reproduce this multiple times and it only happens with the datastore script. I get the same error "ContentProvider callback exception: Unable to dispatch task"

**Comment by matthewdean** [comment]
Going to need reproduction steps for this one

**Comment by The0neThe0nly** [comment]
As far as I know, this has been fixed for a while. Once the crash went away I stopped getting ContentProvider errors in March 2015 but @Anaminus was still getting them. He might have some input.

**Comment by foreverpower** [comment]
This is still an issue. The reproduction steps are already provided in the original post:

1. Open a new place and press the new play solo button.
2. Press the reset button immediately (spam until it's active).
