### ISSUE TITLE
ROBLOX won't start

### ISSUE THREAD

**Issue by Thewsomeguy** [Anaminus/roblox-bug-tracker#519]
I'm running Chrome Version 39.0.2171.62 beta-m, and when I try to start ROBLOX, this comes up:
![Image](http://puu.sh/cS7Xh/acefc570a5.jpg)

But I don't have a plug-in blocked message. This was happening yesterday, too. I reinstalled ROBLOX, and it worked for a bit. Now it's happening again after I started my computer this morning. I think Chrome updated, and it broke something. (If you   noticed, it says "beta-m", that's because I'm in the beta channel)

**Comment by RobloxTechnicalSupport** [comment]
To fix this issues there are a couple things that you can do. Acctully go into your setting and quickly disable all your plugins even if they aren't ad-blockers because sometimes browsers and Roblox get confused and designate add-ons as ad blockers. If this doesn't work another reason might be your settings aren't communicating with Roblox correctly so there should be a reset settings button somewhere in your settings. There are plenty of videos on how to do this. If your game just won't load make sure that you have java and it's up to date I see a lot of clients that have resolved there issue by doing so.

**Comment by Thewsomeguy** [comment]
Can you please not reply to almost 2 year old issues?
