### ISSUE TITLE
fixing and willfix tags are too similar

### ISSUE THREAD

**Issue by matthewdean** [Anaminus/roblox-bug-tracker#557]
I propose that the `fixing` tag be removed in favor of `willfix`. `willfix` should be taken to mean that a staff member has indicated that the bug is going to be fixed.

**Comment by Anaminus** [comment]
That is already what `willfix` indicates. However, it doesn't indicate anything about what's actually being done about the issue internally. Is the issue actually being worked on right this minute, or has it merely been acknowledged, to be fixed at some later time? More accurately, do I need to check the issue periodically to see whether it has been fixed yet, or would doing so just be a waste of time, since the fix date is unspecified?

How about this: I need *some* way to mark issues for periodic checking, so how about I kill the tag and assign myself to these issues? I doubt the assignee system is going to get any other kind of use.

**Comment by Anaminus** [comment]
Alright, done. Since there can't be more than one assignee per issue, collaborators should pretty much continue ignoring the assignee system.
