### ISSUE TITLE
Focus is broken.

### ISSUE THREAD

**Issue by Kinglar** [Anaminus/roblox-bug-tracker#618]
Focus does not work. I am zoomed in all the way. It is a local script, no output.
workspace.CurrentCamera.Focus = Player.Character[limb].CFrame

**Comment by SFOH** [comment]
Exactly how are you using this?

**Comment by Kinglar** [comment]
First person, and I use Focus to go to a body part of someone.

**Comment by SFOH** [comment]
I don't believe that using any camera values while in FP mode will work. Don't quote me however.

**Comment by Kinglar** [comment]
It worked, but now its broken. There is no output

**Comment by JasonTheOwner** [comment]
Try it on the limb only - not the CFrame.  I've only had the camera target work on Parts.

**Comment by Anaminus** [comment]
Focus is meant to be used when the camera doesn't have a CameraSubject. When CameraSubject is set, Focus is supposed to be set as the CFrame of the CameraSubject automatically. There was probably a recent change that ensured this.

It's relatively easy to shift the CFrame of the camera so that it's looking at a part. For example, given a `Camera` and a `Part`, the following snippet is one way to do it:

```lua
Camera.CoordinateFrame = CFrame.new(Camera.Focus.p, Part.CFrame.p)*CFrame.new(0, 0, (Camera.CoordinateFrame.p - Camera.Focus.p).magnitude)
```
