### ISSUE TITLE
AnimationController crash 

### ISSUE THREAD

**Issue by ImageLabel** [Anaminus/roblox-bug-tracker#622]
Instancing a new [`AnimationController`](http://wiki.roblox.com/index.php?title=API:Class/AnimationController)  with no set parent, and then proceeding to use [`LoadAnimation`](http://wiki.roblox.com/index.php?title=API:Class/AnimationController/LoadAnimation) with any "valid" argument (service, non-existent variables, **or actual Animations**) results in ***ROBLOX Studio crashing***.

A running/test server is not *required* to reproduce the bug, just a freshly opened place in edit mode should suffice.

______________________________________
Instance.new("AnimationController"):LoadAnimation(*instance*)

**Comment by The0neThe0nly** [comment]
Roblox crashes because it attempts to access invalid memory (`0x0000001C`). `!exploitable` describes it as `PROBABLY_EXPLOITABLE` because the value of `ECX+0x1C` is called to in a later instruction, however it appears that the crash is not exploitable because the memory at `ECX+0x1C` is not controllable and will always be `NULL`.

In the main subroutine that handles `LoadAnimation`, a `mov` instruction moves memory from the value of `ESI+0x40` into `ECX`. `ESI+0x40`, however, is `NULL`. The `ECX` register becomes `0x00000000` and a call is made to a function related to the `className` property. Within this function it attempts to move memory from the value of `ECX+0x1C` (`ECX` is `NULL`) into `EAX`, which causes a crash. If for some reason the value of `ECX+0x1C` was valid memory, a later instruction calls the value of `EAX+04` which could potentially call to invalid/random memory or it could call to a specified function if someone figured out how to control the memory at `ECX+0x1C` (which seems unlikely).

My guess is that `ESI+0x40` is related to the parent in which `ESI` is the address for the parent object and `0x40` is the location of the className/class object. Another possibility is that `ESI` is the address of the `AnimationController` object and `0x40` is the address of the parent object. `ECX+0x1C` would then probably be a reference to the `className`/class object of the parent object.

A fix for this problem would be to check if the parent of `AnimationController` is `nil`.

Crash location as of May 10th, 2015:
`"RobloxStudioBeta.exe"+0x765405`:
```ASM
mov EDX,DWORD PTR [ESI+0x40] ; ESI+0x40 is NULL (0x00000000).
lea EAX,[EBP-0x30]
push EAX
call "RobloxStudioBeta.exe"+0x32E30 ; call to className property function.
        push EBP
        mov EBP,ESP
        push ECX
        mov EAX,DWORD PTR [ECX+0x1C] ; crash location. ECX is NULL (0x00000000) so it attempts to access 0x0000001C and crashes due to invalid memory.
        add ECX,0x1C
        push ESI
        mov DWORD PTR [EBP-0x04],0x00000000
        call DWORD PTR [EAX+0x04] ; here it may call to invalid/random memory if ECX+0x1C was valid memory. if ECX+0x1C can be controlled, this can be exploited to call to specific functions.
```

**Comment by Anaminus** [comment]
Just to confirm, running the following command in studio will crash:

```lua
Instance.new("AnimationController"):LoadAnimation(nil)
```

**Comment by ImageLabel** [comment]
correct

**Comment by RobloxCodeWriter** [comment]
This should be fixed.

**Comment by Anaminus** [comment]
Confirmed to be fixed.
