### ISSUE TITLE
Rotated Image Label is not properly clipped by containing UI element

### ISSUE THREAD

**Issue by TheSneak** [Anaminus/roblox-bug-tracker#637]
If an image is on a scrolling frame and has its rotation set to a non-zero value, it will not be hidden when it is scrolled out of the frame's viewport.

Here is a video depicting the problem: https://www.youtube.com/watch?v=gHDxHh3o4xA

The top image has a rotation value of zero. As it scrolls up and out of the viewport, it is properly hidden. The bottom image has a rotation of 180. As it scrolls down out of the viewport it is not hidden, but remains visible.

**Comment by Anaminus** [comment]
*Any* rotated GUI will not be clipped. This is intentional. When devs wanted to implement GUI rotation, there was a choice for either just rotation (easier to implement, quicker to release), or rotation+clipping (more complex, takes longer to implement, requires engine overhaul). Based on user feedback, they went with the former.

**Comment by NokiaGuy** [comment]
I don't see why they wouldn't have released the no-clipped rotation quickie, and then put it on the task list to enable clipping (and engine overhaul) later.

**Comment by Anaminus** [comment]
Obviously it's planned in the long term. It would certainly happen at the same time that a new engine is implemented, which there have been discussions about. No promises on when that happens, though.

**Comment by samfun123** [comment]
Shouldn't this get the wontfix/willfix tag instead of invalid?
