### ISSUE TITLE
UserInputService.TextBoxFocused and CoreGUIs

### ISSUE THREAD

**Issue by JodeRBX** [Anaminus/roblox-bug-tracker#646]
TextBoxFocused will allow you to obtain a reference to the TextBox in the Chat CoreGUI. Since this Instance is RobloxLocked, interacting with it in *any way* from a normal, level 2 LocalScript will cause an error. I'm not sure this is a *bug*, per se, but it is definitely not ideal behavior.

**Comment by Anaminus** [comment]
It's not ideal, but it would be much worse to not fire the event at all. This issue is not exclusive to TextBoxFocused, and is a problem with RobloxLocked in general (`FindFirstChild("RobloxGui",true)` for example), but that's a separate issue.

I think you just have to be careful with the returned TextBox. You already have to be careful with anything in the game tree anyway, so it shouldn't hurt too much. If it hasn't been done already, this problem should be mentioned in whatever documentation there is about TextBoxFocused.

**Comment by einsteinK** [comment]
Since a week, the wiki page on TextBoxFocused already mentions this.
I just mentioned it also in TextBoxFocusReleased.
Now both events should aware the user about RobloxLocked objects.
(Assuming people actually read the full wiki page)
