### ISSUE TITLE
Load More Servers button shows, when there's no more servers [website] [bug]

### ISSUE THREAD

**Issue by magiccube3** [Anaminus/roblox-bug-tracker#687]
If you go to a game place which has lets say for example, four servers running
click on the 'servers' tab
at the bottom, the 'load more' button will show
 when you click it, it will say there are no more servers running

The 'load more' button should only show if there are over 10 servers running
(The servers tabs shows 10 servers [if available] by default)

Pictures upon request, but this is pretty straight-forward.

**Comment by samfun123** [comment]
Go to a game that has less than 10 servers active
![loadmoreservers](https://cloud.githubusercontent.com/assets/6759716/9561909/8d57deb6-4e28-11e5-8a24-f6b529528b66.PNG)
Click "Load More"
![loadmoreservers2](https://cloud.githubusercontent.com/assets/6759716/9561910/95a84178-4e28-11e5-8ea3-71db694c4916.PNG)
The problem is that button shouldn't be showing if there isn't any more servers to load.

**Comment by Anaminus** [comment]
I cannot reproduce this in Firefox. There is no Load More button to click.

**Comment by samfun123** [comment]
I used chrome and if I never saw the "Load More" button pressing refresh would show the "Load More" button.
