### ISSUE TITLE
Valid Code Marked Invalid

### ISSUE THREAD

**Issue by ThrownException** [Anaminus/roblox-bug-tracker#725]
When I was optimizing my code, I started replacing :FindFirstChild(admin) with [admin] instead, but the code editor marks this as invalid:

pcall(function() game:GetService('Players')[admin] end)

When that above is the same as:

pcall(function() game:GetService('Players'):FindFirstChild(admin) end)

**Comment by SNCPlay42** [comment]
What if "admin" is "Parent", "ClassName", "Archivable", "FindFirstChild"... etc.?

**Comment by Anaminus** [comment]
1. Your code is invalid syntax. It indexes the Players object, but it doesn't do anything with the result. FindFirstChild is valid because it is a function call, and function calls may or may not have a result to begin with.
2. Indexing an object is fundamentally different from FindFirstChild. Indexing will look first for the name of a property of the object, then the name of the first child in the object, then throwing an error if it can't find anything. It is very rare that you would want to use this to get child objects. FindFirstChild, on the other hand, only looks for the first child, and if it can't find one, returns nil instead of throwing an error.
